KTH/scanned-exams

- backend/api/canvasApiClient.js
- backend/api/router.js
- backend/package.json
- frontend/src/common/api.js
- frontend/src/features/setup-course/SetupScreen.js
- frontend/src/features/setup-course/steps/Dummy.js
This PR includes all endpoints under "/api/courses/:courseId/setup"
- Create a "recommended homepage"
- Create the special assignment
- Publish the examroom
- Publish the assignment
> Setup backend

- Dockerfile
- backend/__test__/importQueue.spec.js
- backend/api/canvasApiClient.js
- backend/api/importQueue.js
- backend/api/processQueueEntry.js
- backend/api/tentaApiClient.js
- backend/app-https.js
- backend/app.js
- backend/importWorker.js
- backend/package.json
- backend/server.js
This PR includes the function that upload pending exams in the queue to Canvas
> Background queue

- backend/__test__/importQueue.spec.js
- backend/api/canvasApiClient.js
- backend/api/importQueue.js
- backend/api/listAllExams.js
- backend/api/processQueueEntry.js
- backend/api/router.js
- backend/api/tentaApiClient.js
- backend/api/transferExams.js
- backend/server.js
- frontend/src/common/FullPageError.js
- frontend/src/common/api.js
- frontend/src/features/import-exams/steps/PrepareImport.js
- frontend/src/features/import-exams/steps/ResolveIssues.js
- frontend/src/features/import-exams/steps/VerifyResults.js
- frontend/src/features/unauthenticated-app/UnauthenticatedApp.js
- tentaapi-mock/app.js
Also testing errors during import. NOTE! Uploading exams is very slow due to upload token generation being very slow.
> Feature reset queue on import

- backend/package-lock.json
- backend/package.json
- backend/server.js
This PR uses [connect-mongodb-session](https://www.npmjs.com/package/connect-mongodb-session) npm package to save sessions in MongoDB. It uses [TTL indexes](https://docs.mongodb.com/manual/core/index-ttl/) under the hood to automatically delete expired sessions from the database
> Save sessions in mongo DB

- backend/api/importQueue.js
- backend/api/listAllExams.js
- backend/api/router.js
Fixes a couple of issues reported by emil. Reference card "Bugg: TypeError: Cannot read property 'find' of null"
> Fix import crash

- backend/api/canvasApiClient.js
- backend/api/router.js
- frontend/src/common/api.js
- frontend/src/features/import-exams/steps/PrepareImport.js
- frontend/src/features/import-exams/steps/ResolveIssues.js
- frontend/src/features/widgets.js
TODO: Use proper endpoint
TODO: Figure out what the flow should be (go to verify or stay on resolve)
> Feature frontend add missing students

- frontend/src/features/import-exams/ImportFlow.js
- frontend/src/features/import-exams/steps/PrepareImport.js
- frontend/src/features/import-exams/steps/ResolveIssues.js
- frontend/src/features/import-exams/steps/VerifyResults.js
- frontend/src/features/setup-course/SetupFlow.js
- frontend/src/features/setup-course/steps/CreateHomePage.js
- frontend/src/features/setup-course/steps/PublishAssignment.js
- frontend/src/features/widgets.js
This PR contains fixes issues reported during testing by @me97esn 
Each fix has a single commit, except the last one which has a cleanup.
We will probably want to rebase this on the other waiting PRs in order to make sure we don't have merge conflicts.
https://confluence.sys.kth.se/confluence/display/TFI/Testresultat+av+v1.0
> Feedback from testing

- frontend/src/common/api.js
Use resetQueries to get proper loading spinner behaviour when changing state in app
> Use resetQueries to reset

- frontend/src/features/import-exams/steps/ResolveIssues.js
> Added button to re-import errors (if there are any)

- backend/api/listAllExams.js
- backend/api/processQueueEntry.js
- backend/api/router.js
- backend/api/setupCourse.js
- backend/api/tentaApiClient.js
- added statusCode param to EndpointError
- handled error on add user
- log import errors with log.error
> Improve errors

- backend/api/importQueue.js
Related to https://trello.com/c/PZXIpzet
> The error was muted and no stack trace logged so using log.error

- backend/api/canvasApiClient.js
- backend/api/processQueueEntry.js
So now we are throwing an ImportError for all error status codes returned by Canvas. Also, all error messages displayed to the end user are user readable.
> Show user friendly error messages but log errors in more detail.

- backend/api/canvasApiClient.js
This PR adds an error message when trying to create an assignment before the exam date.
It also allows creating the assignment on the same date as the exam
> Error when the exam is in the future

- backend/api/permission.js
- frontend/src/common/FullPageError.js
Martin requested an improved error message. I implemented a simple hotfix.
> Suggest solution to permission_denied

- backend/api/endpointHandlers/listAllExams.js
- backend/api/error.js
- backend/api/externalApis/tentaApiClient.js
> Show stack trace when calling  tentaApi.examListByLadokId()

- backend/__test__/error.spec.js
- backend/__test__/listAllExams.spec.js
- backend/__test__/setupCourse.spec.js
- backend/api/endpointHandlers/listAllExams.js
- backend/api/endpointHandlers/setupCourse.js
- backend/package-lock.json
Added test after bug was found in code
https://trello.com/c/sRNzzzdM
> Fix add test get ladok id

- backend/src/api/externalApis/tentaApiClient.ts
- frontend/src/features/import-exams/steps/PrepareImport.tsx
Shows error message when we have issues with Windreams.
To test this, choose the commit 3df420c which provokes an error state.
I did not wrap the TentaApiError in an EndpointError because I wanted this to be a quickfix given that we are trying to wrap things up. Let me know if you want me to polish further.
> Fix show windreams error

- backend/package-lock.json
- backend/package.json
- backend/src/api/error.ts
- backend/src/api/externalApis/canvasApiClient.ts
To test:
1. Check out: 8f9175c
2. Run the following command from terminal: 
```
docker run -p 8000:80 kennethreitz/httpbin
```
This starts a server that answers with 504
Note: I dumbed down the error object for these errors because it contains quite a lot of data due to passing the entire response object. This might be worth a separate discussion.
> Fix show better canvas down error

- .vscode/launch.json
- README.md
- frontend/src/features/unauthenticated-app/UnauthenticatedApp.tsx
New text by the grace of Martin.
> Change intro text

- Dockerfile_backend_test
- backend/jest-mongodb-config.js
- backend/package-lock.json
- backend/package.json
- backend/src/api/importQueue/processQueueEntry.ts
We believe we caused a race condition where the student object update was cleared by concurrent read/write of queue object.
The error message was "Error trying to add student [null] in course [38615]" but the student object should have been set in order to run the code that logs this error. So we believe it was set for a while and then removed in a concurrent write.
> We believe we caused a race condition

- backend/src/api/externalApis/ladokApiClient.ts
- backend/src/server.ts
- backend/src/system.ts
This PR adds an `/_about` page where you can check which Ladok user is used by the app.
It also logs an Error message if Ladok is not reachable
> Check cert

- backend/src/api/endpointHandlers/setupCourse.ts
- backend/src/api/externalApis/canvasApiClient.ts
- backend/src/api/externalApis/ladokApiClient.ts
- backend/src/api/externalApis/tentaApiClient.ts
- frontend/src/features/authenticated-app/AuthenticatedApp.tsx
- frontend/src/features/setup-course/SetupFlow.tsx
- frontend/src/features/setup-course/steps/CreateAssignment.tsx
- frontend/src/features/setup-course/steps/PublishAssignment.tsx
An exam room where the aktivitetstillfälle in Ladok with anonymous grading: https://kth.test.instructure.com/courses/48695
> anonymous grading if set in ladok
